CREATE TABLE POLL_AUDIT
(
    POLL_NAME          VARCHAR(64) PRIMARY KEY,
    NEXT_RUN_TIME      TIMESTAMP,
    NUMBER_OF_RECORDS  INT
);

GRANT SELECT, INSERT, UPDATE, DELETE ON POLL_AUDIT TO offender_events;
